services:
  - type: web
    name: my-static-site
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: oregon
    branch: main
    buildCommand: ""
    startCommand: ""
